### ISSUE TITLE
Please consider adding themes

### ISSUE THREAD

**Issue by lonelygo** [songquanpeng/stats-cards#1]
Refer this repo：https://github.com/anuraghazra/github-readme-stats#all-inbuilt-themes--

**Comment by songquanpeng** [comment]
Good idea, thx. I will consider this.

**Comment by songquanpeng** [comment]
目前已支持暗黑模式：
![image](https://user-images.githubusercontent.com/39998050/143522212-0175b83f-9633-42bd-b45f-420c8e02c1f7.png)
