### ISSUE TITLE
optimization: 名字太长了 导致标题缺失了

### ISSUE THREAD

**Issue by galaxy-sea** [songquanpeng/stats-cards#10]
标题可以居左么.  

![image](https://user-images.githubusercontent.com/30821411/196834590-3c5bc98d-a5ab-498b-aae6-0951695d2a90.png)

**Comment by songquanpeng** [comment]
Okay，需要调整一下模板的 SVG 代码

**Comment by galaxy-sea** [comment]
good  👍

**Comment by songquanpeng** [comment]
居中了：
![image](https://user-images.githubusercontent.com/39998050/196854185-c03cae72-a371-4d5a-9cb6-2a6c5726ba64.png)
