### ISSUE TITLE
只返回请求的具体某个值

### ISSUE THREAD

**Issue by WangRongsheng** [songquanpeng/stats-cards#12]
您好，请问我只需要csdn的粉丝数，请问可以怎么获取该值呢？

**Comment by songquanpeng** [comment]
需要加额外的 API 端口

**Comment by songquanpeng** [comment]
考虑到这个需求比较小众，我的意见是 fork 之后稍微改一下就好了，原本是返回 svg，你改成返回 json 就好了。

**Comment by songquanpeng** [comment]
具体来说，这里直接 return data 就好：
https://github.com/songquanpeng/stats-cards/blob/f6657bfae1e08e40ac23e871d4dcd8d4252f6e1f/render/csdn.js#L3-L21

除此之外，这里的返回类型也要改：
https://github.com/songquanpeng/stats-cards/blob/f6657bfae1e08e40ac23e871d4dcd8d4252f6e1f/api/csdn.js#L8

**Comment by songquanpeng** [comment]
现在在请求 URL 后面加上 `&raw=true` 可获得原始 JSON 数据了。
