### ISSUE TITLE
知乎好像无法监控了，都是传输的无定义

### ISSUE THREAD

**Issue by foryouos** [songquanpeng/stats-cards#14]

**Comment by songquanpeng** [comment]
我刚刚试了下还可以？
![](https://stats.justsong.cn/api/zhihu?username=songwonderful&lang=zh-CN)

请给一个失败例子我看一下。

**Comment by songquanpeng** [comment]
我去你的首页看了一下，我这里显示也是正常的。

不过好像数据不太对，很奇怪。

我下午有空后看一下。

**Comment by foryouos** [comment]
# 是的，数据不对
```Markdown
![](https://stats.justsong.cn/api/zhihu/?id=foryouos&theme=flag-india)
```
![](https://stats.justsong.cn/api/zhihu/?id=foryouos&theme=flag-india)
我的ID是foryouos ,用户名 ：于喝水
结果显示的是  肥魔's Zhihu Stats
我看了它的知乎Id是undefined

我换了其它id之后，显示还是 肥魔's Zhihu Stats

或许是不是id的参数传递失败了

谢谢！

**Comment by songquanpeng** [comment]
![](https://stats.justsong.cn/api/zhihu/?username=foryouos&theme=flag-india)

是 username，而非 id

我还是改一下程序吧，让两个都可以。

**Comment by songquanpeng** [comment]
已修复。

**Comment by foryouos** [comment]
# Thank you
sorry! 粗心大意
