### ISSUE TITLE
Please consider juejin.cn

### ISSUE THREAD

**Issue by jiweiyuan** [songquanpeng/stats-cards#2]
I want to know whether to consider [掘金](https://juejin.cn/), If yes, Maybe I can provide a PR(pull request)

**Comment by songquanpeng** [comment]
Thanks for your interest and PR is always welcome! 

The steps to add a new website are:
1. API controller part, this part is very easy to handle.
2. Crawler part. Basically, there are two ways to do that:
   a. Find & request the API directly.
   b. Parse the HTML.
3. Render part. This part will need an SVG template. You can use Adobe XD or any other tool to design it, or you can leave it to me.

The following attachment is the Adobe XD project file I used.
[Stat Cards.zip](https://github.com/songquanpeng/stats-cards/files/6546078/Stat.Cards.zip)

**Comment by songquanpeng** [comment]
Merged.
