### ISSUE TITLE
缓存问题

### ISSUE THREAD

**Issue by LhdDream** [songquanpeng/stats-cards#4]
问题:
       leetcode 进度更新之后，卡片并没有被更新

**Comment by songquanpeng** [comment]
首先服务器本身为请求设置了10min的缓存，其次 GitHub 本身也会对图片进行缓存（如果你是放在了 GitHub 的 README 中）。前者强制刷新可解，后者只能等 GitHub 更新缓存。

**Comment by LhdDream** [comment]
好的，感谢
