### ISSUE TITLE
B站抓取数据异常

### ISSUE THREAD

**Issue by stvsl** [songquanpeng/stats-cards#5]
无法抓取部分B站数据

**Comment by songquanpeng** [comment]
指的是 Video Views 和 Upvotes 吗？这个是因为我还没搞定怎么解决 B 站的反爬限制。

**Comment by stvsl** [comment]
是的，没错QaQ

**Comment by songquanpeng** [comment]
之后有空了我再搞一下，这个 issue 先开着吧

**Comment by stvsl** [comment]
好的！感谢！

**Comment by songquanpeng** [comment]
已经解决了：
![image](https://user-images.githubusercontent.com/39998050/196882922-46628e83-6d14-41c8-aad2-d876c26af368.png)

**Comment by stvsl** [comment]
感谢感谢😀
