### ISSUE TITLE
掘金签名如果太长的话，字会出去，大佬能不能优化一下

### ISSUE THREAD

**Issue by yuzhouStayHungry** [songquanpeng/stats-cards#6]
![掘金数据](https://stats.justsong.cn/api/juejin?id=3526889034751639)

**Comment by songquanpeng** [comment]
收到

**Comment by songquanpeng** [comment]
![image](https://user-images.githubusercontent.com/39998050/171589659-cce15c73-e466-4c34-97e1-aef67cab335c.png)
