### ISSUE TITLE
知乎用户名有"."似乎不能抓取成功

### ISSUE THREAD

**Issue by henryhuanghenry** [songquanpeng/stats-cards#7]
如题~

**Comment by songquanpeng** [comment]
`https://stats.justsong.cn/api/zhihu?username=mr-henryhuang&theme=dark`
![](https://stats.justsong.cn/api/zhihu?username=mr-henryhuang&theme=dark)

**Comment by henryhuanghenry** [comment]
谢谢大佬！！！！

**Comment by songquanpeng** [comment]
README 已更新，感谢反馈
